### ISSUE TITLE
以热爱祖国为荣、以危害祖国为耻， 以服务人民为荣、以背离人民为耻。

### ISSUE THREAD

**Issue by Uchiha-Peng** [opengl106/project_viral_glycoprotein-pjvirgly#13]
不知道说你点啥好，不管你喜不喜欢这个国家这个民族，你也改变不了你曾经属于我们中间的一份子这个事实。你诋毁的国家，你诋毁的民族，正是这个世界上最了不起的国家、最伟大的民族。虽然我长得也不咋地，但是我想说
![IMG_20200627_214713](https://user-images.githubusercontent.com/20633089/85923681-cd3fdb80-b8bf-11ea-941a-32f7e8009991.jpg)
你真丑。

**Comment by HaleyLeoZhang** [comment]
确实丑。。

**Comment by DeepestAbyss** [comment]
![zb](https://user-images.githubusercontent.com/15101628/85923853-15133280-b8c1-11ea-80a1-48e1cc616465.png)
